import first from './Pictures/first.png';
import second from './Pictures/second.png';
import third from './Pictures/third.png';
import forth from './Pictures/forth.png';
import fifth from './Pictures/fifth.jpg';
import sixth from './Pictures/sixth.jpg';
import seventh from './Pictures/seventh.jpg';
import eighth from './Pictures/eighth.jpg';
import ninth from './Pictures/ninth.jpg';
import tenth from './Pictures/tenth.jpg';
import eleventh from './Pictures/eleventh.jpg';
import twelveth from './Pictures/12.jpg';
import fourteenth from './Pictures/14.jpg';
import fifteenth from './Pictures/15.jpg';
import sixteenth from './Pictures/16.jpg';

const dummyData = [
  {
    img: first,
    price: '$3500',
    name: 'Red Carpet',
    address: 'USA',
    favourite: false,
    movingIn: '02 days',
    bedrooms: '3 Beds',
    bathrooms: '3 Bathrooms',
    area: '815 sqrt',
    type: 'Luxury',
  },
  {
    img: second,
    price: '$6500',
    name: 'Palm Harbor',
    address: 'USA',
    favourite: false,
    movingIn: '04 days',
    bedrooms: '3 Beds',
    bathrooms: '3 Bathrooms',
    area: '865 sqrt',
    type: 'Houses',
  },
  {
    img: third,
    price: '$6000',
    name: 'Faulkner Ave',
    address: 'Japan',
    favourite: false,
    movingIn: '06 days',
    bedrooms: '3 Beds',
    bathrooms: '3 Bathrooms',
    area: '890 sqrt',
    type: 'Apartments',
  },
  {
    img: forth,
    price: '$4000',
    name: 'Majestic Rows',
    address: 'Japan',
    favourite: false,
    movingIn: '08 days',
    bedrooms: '3 Beds',
    bathrooms: '3 Bathrooms',
    area: '815 sqrt',
    type: 'Houses',
  },
  {
    img: fifth,
    price: '$5500',
    name: 'Scrappers',
    address: 'India',
    favourite: false,
    movingIn: '10 days',
    bedrooms: '3 Beds',
    bathrooms: '3 Bathrooms',
    area: '865 sqrt',
    type: 'Apartments',
  },
  {
    img: sixth,
    price: '$6000',
    name: 'Nirvana',
    address: 'India',
    favourite: false,
    movingIn: '12 days',
    bedrooms: '3 Beds',
    bathrooms: '3 Bathrooms',
    area: '890 sqrt',
    type: 'Luxury',
  },
  {
    img: seventh,
    price: '$4000',
    name: 'Raheja',
    address: 'India',
    favourite: false,
    movingIn: '14 days',
    bedrooms: '3 Beds',
    bathrooms: '3 Bathrooms',
    area: '815 sqrt',
    type: 'Apartments',
  },
  {
    img: eighth,
    price: '$4500',
    name: 'Lokhandwala',
    address: 'India',
    favourite: false,
    movingIn: '16 days',
    bedrooms: '3 Beds',
    bathrooms: '3 Bathrooms',
    area: '865 sqrt',
    type: 'Houses',
  },
  {
    img: ninth,
    price: '$5000',
    name: 'Greenville',
    address: 'USA',
    favourite: false,
    movingIn: '18 days',
    bedrooms: '3 Beds',
    bathrooms: '3 Bathrooms',
    area: '890 sqrt',
    type: 'Luxury',
  },
  {
    img: tenth,
    price: '$5500',
    name: 'Pensacola',
    address: 'USA',
    favourite: false,
    movingIn: '20 days',
    bedrooms: '3 Beds',
    bathrooms: '3 Bathrooms',
    area: '815 sqrt',
    type: 'Apartments',
  },
  {
    img: eleventh,
    price: '$4500',
    name: 'Nirvana',
    address: 'USA',
    favourite: false,
    movingIn: '22 days',
    bedrooms: '3 Beds',
    bathrooms: '3 Bathrooms',
    area: '865 sqrt',
    type: 'Houses',
  },
  {
    img: twelveth,
    price: '$6000',
    name: 'Buffalo',
    address: 'USA',
    favourite: false,
    movingIn: '24 days',
    bedrooms: '3 Beds',
    bathrooms: '3 Bathrooms',
    area: '890 sqrt',
    type: 'Luxury',
  },
  {
    img: fourteenth,
    price: '$9000',
    name: 'Kyoto',
    address: 'Japan',
    favourite: false,
    movingIn: '26 days',
    bedrooms: '3 Beds',
    bathrooms: '3 Bathrooms',
    area: '815 sqrt',
    type: 'Apartments',
  },
  {
    img: fifteenth,
    price: '$4000',
    name: 'Yokohama',
    address: 'Japan',
    favourite: false,
    movingIn: '28 days',
    bedrooms: '3 Beds',
    bathrooms: '3 Bathrooms',
    area: '865 sqrt',
    type: 'Houses',
  },
  {
    img: sixteenth,
    price: '$4500',
    name: 'Sapporo',
    address: 'Japan',
    favourite: false,
    movingIn: '30 days',
    bedrooms: '3 Beds',
    bathrooms: '3 Bathrooms',
    area: '890 sqrt',
    type: 'Luxury',
  },
];

export default dummyData;
